anode_02 = ['EEG FP1-LE',
        'EEG F7-LE',
        'EEG T3-LE',
        'EEG T5-LE',
        'EEG FP2-LE',
        'EEG F8-LE',
        'EEG T4-LE',
        'EEG T6-LE',
        'EEG A1-LE',
        'EEG T3-LE',
        'EEG C3-LE',
        'EEG CZ-LE',
        'EEG C4-LE',
        'EEG T4-LE',
        'EEG FP1-LE',
        'EEG F3-LE',
        'EEG C3-LE',
        'EEG P3-LE', 
        'EEG FP2-LE',
        'EEG F4-LE',
        'EEG C4-LE',
        'EEG P4-LE']

cathode_02 = ['EEG F7-LE',
        'EEG T3-LE',
        'EEG T5-LE',
        'EEG O1-LE',
        'EEG F8-LE',
        'EEG T4-LE',
        'EEG T6-LE',
        'EEG O2-LE',
        'EEG T3-LE',
        'EEG C3-LE',
        'EEG CZ-LE',
        'EEG C4-LE',
        'EEG T4-LE',
        'EEG A2-LE',
        'EEG F3-LE',
        'EEG C3-LE',
        'EEG P3-LE', 
        'EEG O1-LE',
        'EEG F4-LE',
        'EEG C4-LE',
        'EEG P4-LE',
        'EEG O2-LE']

bipolar_ch_names_02 = ['FP1-F7',
                   'F7-T3',
                   'T3-T5',
                   'T5-O1',
                   'FP2-F8',
                   'F8-T4',
                   'T4-T6',
                   'T6-O2',
                   'A1-T3',
                   'T3-C3',
                   'C3-CZ',
                   'CZ-C4',
                   'C4-T4',
                   'T4-A2',
                   'FP1-F3',
                   'F3-C3',
                   'C3-P3',
                   'P3-O1',
                   'FP2-F4',
                   'F4-C4',
                   'C4-P4',
                   'P4-O2']


anode_04 = ['EEG FP1-LE',
        'EEG F7-LE',
        'EEG T3-LE',
        'EEG T5-LE',
        'EEG FP2-LE',
        'EEG F8-LE',
        'EEG T4-LE',
        'EEG T6-LE',
        'EEG T3-LE',
        'EEG C3-LE',
        'EEG CZ-LE',
        'EEG C4-LE',
        'EEG FP1-LE',
        'EEG F3-LE',
        'EEG C3-LE',
        'EEG P3-LE', 
        'EEG FP2-LE',
        'EEG F4-LE',
        'EEG C4-LE',
        'EEG P4-LE']

cathode_04 = ['EEG F7-LE',
        'EEG T3-LE',
        'EEG T5-LE',
        'EEG O1-LE',
        'EEG F8-LE',
        'EEG T4-LE',
        'EEG T6-LE',
        'EEG O2-LE',
        'EEG C3-LE',
        'EEG CZ-LE',
        'EEG C4-LE',
        'EEG T4-LE',
        'EEG F3-LE',
        'EEG C3-LE',
        'EEG P3-LE', 
        'EEG O1-LE',
        'EEG F4-LE',
        'EEG C4-LE',
        'EEG P4-LE',
        'EEG O2-LE']

bipolar_ch_names_04 = ['FP1-F7',
                   'F7-T3',
                   'T3-T5',
                   'T5-O1',
                   'FP2-F8',
                   'F8-T4',
                   'T4-T6',
                   'T6-O2',
                   'T3-C3',
                   'C3-CZ',
                   'CZ-C4',
                   'C4-T4',
                   'FP1-F3',
                   'F3-C3',
                   'C3-P3',
                   'P3-O1',
                   'FP2-F4',
                   'F4-C4',
                   'C4-P4',
                   'P4-O2']




anode_01 = ['EEG FP1-REF',
        'EEG F7-REF',
        'EEG T3-REF',
        'EEG T5-REF',
        'EEG FP2-REF',
        'EEG F8-REF',
        'EEG T4-REF',
        'EEG T6-REF',
        'EEG A1-REF',
        'EEG T3-REF',
        'EEG C3-REF',
        'EEG CZ-REF',
        'EEG C4-REF',
        'EEG T4-REF',
        'EEG FP1-REF',
        'EEG F3-REF',
        'EEG C3-REF',
        'EEG P3-REF', 
        'EEG FP2-REF',
        'EEG F4-REF',
        'EEG C4-REF',
        'EEG P4-REF']

cathode_01 = ['EEG F7-REF',
        'EEG T3-REF',
        'EEG T5-REF',
        'EEG O1-REF',
        'EEG F8-REF',
        'EEG T4-REF',
        'EEG T6-REF',
        'EEG O2-REF',
        'EEG T3-REF',
        'EEG C3-REF',
        'EEG CZ-REF',
        'EEG C4-REF',
        'EEG T4-REF',
        'EEG A2-REF',
        'EEG F3-REF',
        'EEG C3-REF',
        'EEG P3-REF', 
        'EEG O1-REF',
        'EEG F4-REF',
        'EEG C4-REF',
        'EEG P4-REF',
        'EEG O2-REF']

bipolar_ch_names_01 = ['FP1-F7',
                   'F7-T3',
                   'T3-T5',
                   'T5-O1',
                   'FP2-F8',
                   'F8-T4',
                   'T4-T6',
                   'T6-O2',
                   'A1-T3',
                   'T3-C3',
                   'C3-CZ',
                   'CZ-C4',
                   'C4-T4',
                   'T4-A2',
                   'FP1-F3',
                   'F3-C3',
                   'C3-P3',
                   'P3-O1',
                   'FP2-F4',
                   'F4-C4',
                   'C4-P4',
                   'P4-O2']


anode_03 = ['EEG FP1-REF',
        'EEG F7-REF',
        'EEG T3-REF',
        'EEG T5-REF',
        'EEG FP2-REF',
        'EEG F8-REF',
        'EEG T4-REF',
        'EEG T6-REF',
        'EEG T3-REF',
        'EEG C3-REF',
        'EEG CZ-REF',
        'EEG C4-REF',
        'EEG FP1-REF',
        'EEG F3-REF',
        'EEG C3-REF',
        'EEG P3-REF', 
        'EEG FP2-REF',
        'EEG F4-REF',
        'EEG C4-REF',
        'EEG P4-REF']

cathode_03 = ['EEG F7-REF',
        'EEG T3-REF',
        'EEG T5-REF',
        'EEG O1-REF',
        'EEG F8-REF',
        'EEG T4-REF',
        'EEG T6-REF',
        'EEG O2-REF',
        'EEG C3-REF',
        'EEG CZ-REF',
        'EEG C4-REF',
        'EEG T4-REF',
        'EEG F3-REF',
        'EEG C3-REF',
        'EEG P3-REF', 
        'EEG O1-REF',
        'EEG F4-REF',
        'EEG C4-REF',
        'EEG P4-REF',
        'EEG O2-REF']

bipolar_ch_names_03 = ['FP1-F7',
                   'F7-T3',
                   'T3-T5',
                   'T5-O1',
                   'FP2-F8',
                   'F8-T4',
                   'T4-T6',
                   'T6-O2',
                   'T3-C3',
                   'C3-CZ',
                   'CZ-C4',
                   'C4-T4',
                   'FP1-F3',
                   'F3-C3',
                   'C3-P3',
                   'P3-O1',
                   'FP2-F4',
                   'F4-C4',
                   'C4-P4',
                   'P4-O2']


anode = [anode_01, anode_02, anode_03, anode_04]
cathode = [cathode_01, cathode_02, cathode_03, cathode_04]
bipolar_ch_names = [bipolar_ch_names_01, bipolar_ch_names_02, bipolar_ch_names_03, bipolar_ch_names_04]
